# https://github.com/DiUS/pact_broker-docker
version: "3"
services:
  postgres:
    image: postgres
    ports:
    - "5422:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

  broker_app:
    image: dius/pact-broker:2.35.0-1
    links:
    - postgres
    ports:
      - "80:80"
    environment:
      PACT_BROKER_DATABASE_USERNAME: postgres
      PACT_BROKER_DATABASE_PASSWORD: password
      PACT_BROKER_DATABASE_HOST: postgres
      PACT_BROKER_DATABASE_NAME: postgres
